# -*- coding: utf-8 -*-
"""GenAI_Assign1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRzCQBrNtruFDc3AtXJz_qZw7WAiXaWU
"""

import random
import re
from collections import defaultdict

text = """
Artificial intelligence is transforming the world.
Machine learning is a subset of artificial intelligence.
Artificial intelligence helps in automation and decision making.
Machine learning models learn from data.
"""

text = text.lower()
text = re.sub(r'[^a-z\s]', '', text)
words = text.split()

markov_chain = defaultdict(list)

for i in range(len(words) - 2):
    state = (words[i], words[i + 1])
    next_word = words[i + 2]
    markov_chain[state].append(next_word)

def generate_text(chain, length=40):
    state = random.choice(list(chain.keys()))
    result = [state[0], state[1]]

    for _ in range(length):
        next_words = chain.get(state)
        if not next_words:
            break

        next_word = random.choice(next_words)
        result.append(next_word)
        state = (state[1], next_word)

    return " ".join(result)

print(generate_text(markov_chain, 40))